### ISSUE TITLE
Can't Access Miner Fees

### ISSUE THREAD

**Issue by Silvrbckw** [Pandapip1/eipw-vscode#169]

**Comment by Silvrbckw** [comment]
I have been mining and investing in eth for over 4 months and running into debt now. How do I get access to my mining funds for node I have?

**Comment by Pandapip1** [comment]
> I have been mining and investing in eth for over 4 months and running into debt now. How do I get access to my mining funds for node I have?

This is the wrong place to ask. But you should be able to withdraw when the Shanghai hard fork happens today.
