### ISSUE TITLE
Publish on vscode marketplace?

### ISSUE THREAD

**Issue by xinbenlv** [Pandapip1/eipw-vscode#174]
This is great, why haven't it been published?

Update: oh you already did: https://marketplace.visualstudio.com/items?itemName=pandapip1.eipw-vscode

Let me make it more obvious: #175

**Comment by xinbenlv** [comment]
But it seems I couldn't trigger this extension to warn me for errors in my VS Code. do I need to do anything other than install it from vs code marketplace?

<img width="1882" alt="image" src="https://github.com/Pandapip1/eipw-vscode/assets/640325/b59c3b38-4171-497b-822b-f8bc628c7b1c">

<img width="1882" alt="image" src="https://github.com/Pandapip1/eipw-vscode/assets/640325/70c3c3f0-d78e-46df-b629-06742fbecae6">

**Comment by Pandapip1** [comment]
This was built with an early version of eipw, so e.g. link checking isn't implemented and warnings are hardcoded. I should release a new version.

**Comment by xinbenlv** [comment]
That's great. Don't forget to publish the new version on https://marketplace.visualstudio.com/items?itemName=pandapip1.eipw-vscode

**Comment by Pandapip1** [comment]
> That's great. Don't forget to publish the new version on https://marketplace.visualstudio.com/items?itemName=pandapip1.eipw-vscode

CI does that for me.
